In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('IMDb_Top_700_Movies_2026.csv')

In [4]:
df.head()

,Rank,Title,Year,Genre(s),Director,Main Actor(s),Country,IMDb Rating,Votes,Runtime (mins)
0,1,The Shawshank Redemption,1994,Drama,Frank Darabont,Tim Robbins|Morgan Freeman|Bob Gunton,DK|AT,9.3,3219532,142
1,2,The Godfather,1972,Crime|Drama,Francis Ford Coppola,Marlon Brando|Al Pacino|James Caan,DK|AT,9.2,2244476,175
2,3,The Dark Knight,2008,Crime|Thriller,Christopher Nolan,Christian Bale|Heath Ledger|Aaron Eckhart,DK|LV,9.1,3205233,152
3,4,The Lord of the Rings: The Return of the King,2003,Adventure|Drama|Fantasy,Peter Jackson,Elijah Wood|Viggo Mortensen|Ian McKellen,DK|MK,9.0,2181911,201
4,5,Schindler's List,1993,Biography|Drama|History,Steven Spielberg,Liam Neeson|Ralph Fiennes|Ben Kingsley,DK|LV,9.0,1595992,195

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            700 non-null    int64
 1   Title           700 non-null    str
 2   Year            700 non-null    int64
 3   Genre(s)        700 non-null    str
 4   Director        700 non-null    str
 5   Main Actor(s)   690 non-null    str
 6   Country         700 non-null    str
 7   IMDb Rating     700 non-null    float64
 8   Votes           700 non-null    int64
 9   Runtime (mins)  700 non-null    int64
dtypes: float64(1), int64(4), str(5)
memory usage: 54.8 KB

In [6]:
df.isnull().sum()

Rank               0
Title              0
Year               0
Genre(s)           0
Director           0
Main Actor(s)     10
Country            0
IMDb Rating        0
Votes              0
Runtime (mins)     0
dtype: int64

In [7]:
df.describe()

            Rank         Year  IMDb Rating         Votes  Runtime (mins)
count  700.00000   700.000000   700.000000  7.000000e+02      700.000000
mean   350.50000  1998.038571     8.000143  5.330973e+05      127.360000
std    202.21688    21.347254     0.316657  4.692722e+05       29.101895
min      1.00000  1921.000000     7.500000  5.196400e+04       68.000000
25%    175.75000  1989.000000     7.800000  1.982610e+05      106.000000
50%    350.50000  2004.000000     8.000000  3.988475e+05      123.000000
75%    525.25000  2013.250000     8.200000  7.285130e+05      143.000000
max    700.00000  2026.000000     9.300000  3.219532e+06      321.000000

In [24]:
df['Genre(s)'].unique()

<StringArray>
[                      'Drama',                 'Crime|Drama',
              'Crime|Thriller',     'Adventure|Drama|Fantasy',
     'Biography|Drama|History',   'Adventure|Sci-Fi|Thriller',
        'Crime|Drama|Thriller',               'Drama|Romance',
      'Adventure|Drama|Sci-Fi',               'Action|Sci-Fi',
 ...
   'Adventure|Fantasy|Romance',      'Drama|Thriller|Western',
            'Action|Adventure',         'Biography|Drama|War',
         'Drama|Fantasy|Music',  'Documentary|Drama|Thriller',
              'Comedy|Western',         'Drama|Music|Musical',
 'Biography|Crime|Documentary',              'Fantasy|Horror']
Length: 179, dtype: str

In [26]:
df['Country'].unique()

<StringArray>
['DK|AT', 'DK|LV', 'DK|MK', 'LV|DK', 'LV|PH', 'CR|LV', 'LV|AT', 'DK|PH',
 'HN|DO', 'LU|MK', 'PH|PT', 'AT|PH', 'DK|PT', 'PH|ZA', 'AT|MK', 'ZA|AU',
 'DK|CR', 'NZ|IN', 'LV|MK', 'LU|AT', 'CR|DK', 'MK|FR', 'PT|ZA', 'AT|PT',
 'MK|PH', 'LV|LU', 'LV|PT', 'DK|LU', 'PT|NO', 'PH|NO', 'AU|FR', 'DK|ZA',
 'PL|NZ', 'ZA|AR', 'AT|ZA', 'NZ|US', 'PL|US', 'PT|PH', 'NO|ZA', 'LV|ZA']
Length: 40, dtype: str

In [25]:
df['Director'].unique()

<StringArray>
[                'Frank Darabont',           'Francis Ford Coppola',
              'Christopher Nolan',                  'Peter Jackson',
               'Steven Spielberg',                   'Sidney Lumet',
                  'David Fincher',                'Robert Zemeckis',
              'Quentin Tarantino', 'Lana Wachowski|Lilly Wachowski',
 ...
                   'Stephen Chow',                  'Justine Triet',
                    'Neil Burger',                  'Aditya Chopra',
               'Takashi Yamazaki',                 'Kevin Reynolds',
                 'Louie Psihoyos',          'Henri-Georges Clouzot',
                'Wolfgang Becker',                    'F.W. Murnau']
Length: 407, dtype: str

In [28]:
df['Genre(s)'].value_counts()

Genre(s)
Drama                          39
Crime|Drama|Mystery            26
Crime|Drama                    23
Adventure|Animation|Comedy     23
Drama|Romance                  20
                               ..
Documentary|Drama|Thriller      1
Comedy|Western                  1
Drama|Music|Musical             1
Biography|Crime|Documentary     1
Fantasy|Horror                  1
Name: count, Length: 179, dtype: int64